version: '3'

services:
   db:
     build: 
      context: .
      dockerfile: Dockerfile
     container_name: sample-sql-server
     ports:
      - "1433:1433"
     environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password
     volumes:
      - ./backup:/var/opt/mssql/backup
      - ./outputs:/usr/src/outputs
